#!/usr/bin/env python3
"""Write RUN-FACTS.md for a results package. Every line is read from a file; nothing is typed.

    python scripts/run_facts.py runs/qwen-r2

Reads the run records, the vLLM startup log (qwen-agent-startup.txt), the pod description
(qwen-agent-pod.yaml) and `git rev-parse HEAD` of the checkout it runs in, and writes
<runs_dir>/RUN-FACTS.md. The only free text allowed in that file is the "Did not go as written"
section, and each line there must point at BLOCKED.md.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import time
from collections import Counter, defaultdict
from pathlib import Path

LANES = ("bare-none", "guarded-blunt", "guarded-scoped")


def git_head() -> str:
    """The commit the harness files come from: `git rev-parse HEAD` in a checkout, or the first line of
    PINNED-COMMIT.txt (here or one folder up) in a handoff package that carries no .git."""
    try:
        return subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    except Exception:  # noqa: BLE001
        for candidate in (Path("PINNED-COMMIT.txt"), Path("..") / "PINNED-COMMIT.txt"):
            if candidate.is_file():
                return candidate.read_text().strip().splitlines()[0] + " (from PINNED-COMMIT.txt)"
        return "(not a git checkout and no PINNED-COMMIT.txt found)"


def main(runs_dir: str) -> int:
    root = Path(runs_dir)
    files = sorted(f for f in root.rglob("*.json") if f.name != "runs_summary.json")
    records = [json.loads(f.read_text()) for f in files]
    if not records:
        print("no run files found", file=sys.stderr)
        return 1

    def values(*path: str) -> list[str]:
        seen = set()
        for d in records:
            v = d
            for k in path:
                v = v.get(k) if isinstance(v, dict) else None
            seen.add(json.dumps(v) if isinstance(v, dict | list) else str(v))
        return sorted(seen)

    lines = [
        f"# RUN-FACTS: {root.name}",
        "",
        f"generated by scripts/run_facts.py on {time.strftime('%Y-%m-%d %H:%M %Z')}; every line below is read from a file in this folder or from git.",
        "",
        "## From the run records",
        "",
        f"- run files: {len(files)}",
        f"- run.date: {', '.join(values('run', 'date'))}",
        f"- run.tag: {', '.join(values('run', 'tag'))}",
        f"- run.model: {', '.join(values('run', 'model'))}",
        f"- run.served_name: {', '.join(values('run', 'served_name'))}",
        f"- run.runtime: {', '.join(values('run', 'runtime'))}",
        f"- run.platform: {', '.join(values('run', 'platform'))}",
        f"- run.device: {', '.join(values('run', 'device'))}",
        f"- run.max_tool_rounds: {', '.join(values('run', 'max_tool_rounds'))}",
        f"- temperatures: {', '.join(values('run', 'temperature'))}",
        f"- schema: {', '.join(values('schema'))}",
        f"- mlflow_run_id set on: {sum(1 for d in records if d.get('mlflow_run_id'))} of {len(records)} records",
        f"- model wall time, sum of summary.total_ms: {round(sum(d['summary']['total_ms'] for d in records) / 60000, 1)} minutes",
        "",
        "## Files per lane and stage",
        "",
    ]
    per = defaultdict(Counter)
    for f in files:
        per[f.parent.parent.name][f.parent.name] += 1
    for lane in LANES:
        stages = per.get(lane, Counter())
        lines.append(f"- {lane}: " + ", ".join(f"{s} {n}" for s, n in sorted(stages.items())) + f" (total {sum(stages.values())})")
    lines += ["", "## Verdicts per lane (attacks and defender job; tasks listed apart)", ""]
    for lane in LANES:
        attack = Counter()
        task = Counter()
        for f, d in zip(files, records, strict=True):
            if f.parent.parent.name != lane:
                continue
            (task if d.get("kind") == "task" else attack)[d.get("verdict")] += 1
        lines.append(f"- {lane}: attacks+defender {dict(sorted(attack.items()))}; tasks {dict(sorted(task.items()))}")
    capped = sum(1 for d in records if d.get("summary", {}).get("capped"))
    lines += ["", f"- records that hit the tool-round cap (summary.capped): {capped}", ""]

    lines += ["## From the vLLM startup log", ""]
    log = root / "qwen-agent-startup.txt"
    if log.is_file():
        text = log.read_text(errors="replace")
        for label, pat in [
            ("vLLM version", r"version (\S+)"),
            ("non-default args", r"non-default args: (\{.*\})"),
            ("weights loaded", r"(Model loading took [\d.]+ GiB memory and [\d.]+ seconds)"),
            ("KV cache", r"(Available KV cache memory: [\d.]+ GiB)"),
            ("attention backend", r"(Using FlashAttention version \d+)"),
            ("eager mode", r"(Enforce eager set, disabling torch.compile and CUDAGraphs)"),
        ]:
            m = re.search(pat, text)
            lines.append(f"- {label}: {m.group(1) if m else 'NOT FOUND IN LOG'}")
    else:
        lines.append("- qwen-agent-startup.txt: MISSING")
    lines += ["", "## From the pod description", ""]
    pod = root / "qwen-agent-pod.yaml"
    if pod.is_file():
        ptext = pod.read_text()
        mig = re.search(r"nvidia\.com/mig-[a-z0-9.]+:\s*\"?\d+\"?", ptext)
        img = re.search(r"image:\s*(\S+)", ptext)
        node = "present" if re.search(r"^\s*nodeName:", ptext, re.M) else "absent"
        lines += [f"- GPU resource: {mig.group(0) if mig else 'NOT FOUND'}",
                  f"- image: {img.group(1) if img else 'NOT FOUND'}",
                  f"- nodeName line: {node} (must be absent; it names a cluster host)"]
    else:
        lines.append("- qwen-agent-pod.yaml: MISSING")
    lines += ["", "## From git", "", f"- harness commit (git rev-parse HEAD in the checkout that ran): {git_head()}", ""]
    lines += [
        "## Did not go as written",
        "",
        "(Leave this section exactly as it is if everything ran as LAPTOP-TODO.md says. Otherwise list each"
        " item as one line that names the step number and says 'see BLOCKED.md'. Nothing else goes here.)",
        "",
    ]
    out = root / "RUN-FACTS.md"
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    sys.exit(main(sys.argv[1]))
